resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/7.yaml

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- .
- packages/bigquery
- packages/google-monad
- packages/logging-truck-google
- packages/pubsub

extra-deps:
- git: https://github.com/brendanhay/gogol.git
  commit: 494098af1709d32b75b0be41157547ae7a2bd89d
  subdirs:
  - lib/gogol
  - lib/gogol-core
  - lib/services/gogol-bigquery
  - lib/services/gogol-pubsub
- git: https://github.com/psuggate/logging-truck.git
  # commit: 6e6b9d93ec5d203babdb7ca0932fe4fda9ed70e3
  commit: e835dd01bd67dc15a5c4c9417bcde8a78bb95bce
- co-log-core-0.3.1.0@sha256:9794bdedd1391decd0e22bdfe2b11abcb42e6cff7a4531e1f8882890828f4e63,3816

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.7"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
