resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/15.yaml

packages:
- .
- packages/bigquery
- packages/google-monad
- packages/logging-truck-google
- packages/pubsub

extra-deps:
- git: https://github.com/brendanhay/gogol.git
  commit: 494098af1709d32b75b0be41157547ae7a2bd89d
  subdirs:
  - lib/gogol
  - lib/gogol-core
  - lib/services/gogol-bigquery
  - lib/services/gogol-pubsub
- git: https://github.com/psuggate/logging-truck.git
  commit: fe2a8d894c3102091880d254c8ce653bbf9ed4b4
- co-log-core-0.3.1.0@sha256:9794bdedd1391decd0e22bdfe2b11abcb42e6cff7a4531e1f8882890828f4e63,3816

# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# system-ghc: true
compiler-check: newer-minor

# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
