name:                bigquery
version:             0.1.0.12
license:             BSD3
author:              "Patrick Suggate"
maintainer:          "patrick.suggate@gmail.com"
copyright:           "2022 SixthSense NZ Ltd"

extra-source-files:
- README.md

synopsis:            Short description of your package
category:            Web
description:         Please see the README on GitHub at <https://github.com/githubabuser/google-cloud#readme>

ghc-options:
- -Wall

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- gogol
- gogol-bigquery
- gogol-core
- google-monad
- http-api-data
- lens
- mtl
- openapi3
- relude
- resourcet
- unliftio-core
- unordered-containers

library:
  source-dirs: src

executables:
  bigquery-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bigquery
    - optparse-applicative
    - yaml

tests:
  bigquery-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - bigquery
