name:                google-monad
version:             0.1.0.5
license:             BSD3
author:              "Patrick Suggate"
maintainer:          "patrick.suggate@gmail.com"
copyright:           "2021 SixthSense NZ Ltd"

extra-source-files:
- README.md

synopsis:            Short description of your package
category:            Web
description:         Please see the README on GitHub at <https://github.com/githubabuser/google-cloud#readme>

ghc-options:
- -Wall

dependencies:
- aeson
- base >= 4.7 && < 5
- gogol
- gogol-core
- http-api-data
- lens
- mtl
- openapi3
- relude
- resourcet
- uuid
- unliftio-core

library:
  source-dirs: src
