name:                pubsub
version:             0.1.0.3
github:              "psuggate/some-google"
license:             BSD3
author:              "Patrick Suggate"
maintainer:          "patrick.suggate@gmail.com"
copyright:           "2022 Patrick Suggate"

extra-source-files:
- README.md

synopsis:            Short description of your package
category:            Web
description:         Please see the README on GitHub at <https://github.com/psuggate/some-google/packages/pubsub#readme>

ghc-options:
- -Wall

dependencies:
- aeson
- base >= 4.7 && < 5
- gogol
- gogol-core
- gogol-pubsub
- google-monad
- lens
- logging-truck
- relude

library:
  source-dirs: src

tests:
  pubsub-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - pubsub
